[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[dependencies]
libgit2-sys = { path = "../libgit2-sys" }
libc = "0.2"

[build-dependencies]
ctest = { git = "https://github.com/alexcrichton/ctest" }
